import { User, Project } from './types';

export const defaultUsers: User[] = [
  {
    id: 'u1',
    username: 'admin',
    password: 'admin123',
    role: 'admin',
    name: 'Admin User',
    assignedProjects: ['p1', 'p2', 'p3', 'p4', 'p5'],
  },
  {
    id: 'u2',
    username: 'worker1',
    password: 'worker123',
    role: 'worker',
    name: 'John Worker',
    assignedProjects: ['p1', 'p2'],
  },
  {
    id: 'u3',
    username: 'worker2',
    password: 'worker123',
    role: 'worker',
    name: 'Sarah Builder',
    assignedProjects: ['p3', 'p4'],
  },
  {
    id: 'u4',
    username: 'visitor',
    password: 'visitor123',
    role: 'visitor',
    name: 'Client Viewer',
    assignedProjects: ['p1', 'p3'],
  },
];

export const defaultProjects: Project[] = [
  {
    id: 'p1',
    name: 'E-Commerce Platform Redesign',
    clientName: 'TechCorp Inc.',
    clientUserId: 'CLI-2024-001',
    amount: 15000,
    account: 'ACC-7891',
    cms: 'WordPress + WooCommerce',
    orderStatus: 'in-progress',
    information: 'Complete redesign of the e-commerce platform with new UI/UX, payment gateway integration, and mobile responsiveness.',
    responsible: 'John Worker',
    incDate: '2024-11-28',
    percentage: 50,
    orderPageUrl: 'https://example.com/orders/001',
    spreadsheetLink: 'https://docs.google.com/spreadsheets/d/abc123',
    assignBy: 'Admin User',
    deliLastTime: '2025-02-28',
    progressEntries: [
      { id: 'pe1', date: '2024-12-01', description: 'Project kickoff and requirements gathering completed', percentage: 10, updatedBy: 'u2' },
      { id: 'pe2', date: '2024-12-10', description: 'Wireframes and mockups approved by client', percentage: 25, updatedBy: 'u2' },
      { id: 'pe3', date: '2024-12-20', description: 'Frontend development in progress - homepage and product pages done', percentage: 50, updatedBy: 'u2' },
    ],
    overallProgress: 50,
    createdAt: '2024-11-28',
    updatedAt: '2024-12-20',
    assignedWorkers: ['u2'],
    category: 'Web Development',
  },
  {
    id: 'p2',
    name: 'Mobile App Development',
    clientName: 'StartupXYZ',
    clientUserId: 'CLI-2024-002',
    amount: 25000,
    account: 'ACC-4562',
    cms: 'React Native + Firebase',
    orderStatus: 'in-progress',
    information: 'Cross-platform mobile application for food delivery service with real-time tracking and payment integration.',
    responsible: 'John Worker',
    incDate: '2024-11-10',
    percentage: 30,
    orderPageUrl: 'https://example.com/orders/002',
    spreadsheetLink: 'https://docs.google.com/spreadsheets/d/def456',
    assignBy: 'Admin User',
    deliLastTime: '2025-03-15',
    progressEntries: [
      { id: 'pe4', date: '2024-11-15', description: 'App architecture planned and approved', percentage: 15, updatedBy: 'u2' },
      { id: 'pe5', date: '2024-12-05', description: 'Authentication and user registration module completed', percentage: 30, updatedBy: 'u2' },
    ],
    overallProgress: 30,
    createdAt: '2024-11-10',
    updatedAt: '2024-12-05',
    assignedWorkers: ['u2'],
    category: 'Mobile Development',
  },
  {
    id: 'p3',
    name: 'Corporate Website',
    clientName: 'GlobalFinance Ltd.',
    clientUserId: 'CLI-2024-003',
    amount: 8000,
    account: 'ACC-3345',
    cms: 'Next.js + Contentful',
    orderStatus: 'review',
    information: 'Professional corporate website with company profile, services pages, team section, blog, and contact forms.',
    responsible: 'Sarah Builder',
    incDate: '2024-10-01',
    percentage: 90,
    orderPageUrl: 'https://example.com/orders/003',
    spreadsheetLink: 'https://docs.google.com/spreadsheets/d/ghi789',
    assignBy: 'Admin User',
    deliLastTime: '2025-01-10',
    progressEntries: [
      { id: 'pe6', date: '2024-10-15', description: 'Design phase completed', percentage: 20, updatedBy: 'u3' },
      { id: 'pe7', date: '2024-11-01', description: 'All pages developed and CMS integrated', percentage: 70, updatedBy: 'u3' },
      { id: 'pe8', date: '2024-11-20', description: 'Testing and bug fixes done, submitted for client review', percentage: 90, updatedBy: 'u3' },
    ],
    overallProgress: 90,
    createdAt: '2024-10-01',
    updatedAt: '2024-11-20',
    assignedWorkers: ['u3'],
    category: 'Web Development',
  },
  {
    id: 'p4',
    name: 'SEO & Digital Marketing',
    clientName: 'LocalShop',
    clientUserId: 'CLI-2024-004',
    amount: 3500,
    account: 'ACC-9987',
    cms: 'WordPress',
    orderStatus: 'completed',
    information: 'Complete SEO audit, on-page optimization, Google Ads campaign setup, and social media marketing strategy.',
    responsible: 'Sarah Builder',
    incDate: '2024-08-25',
    percentage: 100,
    orderPageUrl: 'https://example.com/orders/004',
    spreadsheetLink: 'https://docs.google.com/spreadsheets/d/jkl012',
    assignBy: 'Admin User',
    deliLastTime: '2024-10-30',
    progressEntries: [
      { id: 'pe9', date: '2024-09-01', description: 'SEO audit completed', percentage: 25, updatedBy: 'u3' },
      { id: 'pe10', date: '2024-09-20', description: 'On-page optimizations applied', percentage: 50, updatedBy: 'u3' },
      { id: 'pe11', date: '2024-10-10', description: 'Google Ads campaigns launched', percentage: 75, updatedBy: 'u3' },
      { id: 'pe12', date: '2024-10-30', description: 'All deliverables completed and handed over', percentage: 100, updatedBy: 'u3' },
    ],
    overallProgress: 100,
    createdAt: '2024-08-25',
    updatedAt: '2024-10-30',
    assignedWorkers: ['u3'],
    category: 'Digital Marketing',
  },
  {
    id: 'p5',
    name: 'Agency Portfolio Website',
    clientName: 'CreativeStudio',
    clientUserId: 'CLI-2024-005',
    amount: 6000,
    account: 'ACC-5567',
    cms: 'Gatsby + Strapi',
    orderStatus: 'pending',
    information: 'Modern portfolio website showcasing creative work, case studies, team profiles, and contact section with animated transitions.',
    responsible: '',
    incDate: '2024-12-22',
    percentage: 0,
    orderPageUrl: '',
    spreadsheetLink: '',
    assignBy: 'Admin User',
    deliLastTime: '2025-04-01',
    progressEntries: [],
    overallProgress: 0,
    createdAt: '2024-12-22',
    updatedAt: '2024-12-22',
    assignedWorkers: [],
    category: 'Web Development',
  },
];
